apiVersion: v1
stringData:
  MYSQL_DATABASE: "{{ .Values.mariadb.env.database }}"
  MYSQL_PASSWORD: "{{ .Values.mariadb.env.password }}"
  MYSQL_ROOT_PASSWORD: "{{ .Values.mariadb.env.rootPassword }}"
  MYSQL_USER: "{{ .Values.mariadb.env.user }}"
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: default